version: "3"

networks:
  loki:
  # elastic:
  #   driver: bridge

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes: 
      - "D:/projects/Research/Observability/_Metrics/prometheus.yaml:/etc/prometheus/prometheus.yaml"
    networks:
      - loki

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200 
      - ES_TAGS_AS_FIELDS_ALL=true
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - loki

  # tempo:
  #   image: grafana/tempo:latest
  #   environment:
  #     - COLLECTOR_ZIPKIN_HTTP_PORT=9411
  #   ports: 
  #     - "6831:6831/udp"
  #     - "14268:14268"
  #     - "9411:9411"
  #   volumes:
  #     - "D:/projects/Research/Observability/_Metrics/tempo.yaml:/etc/tempo-local.yaml"
  #   command: -config.file=/etc/tempo-local.yaml
  #   networks:
  #     - loki

  # tempo-query:
  #   image: grafana/tempo-query:latest
  #   ports: 
  #     - "16686:16686"
  #   volumes: 
  #     - "D:/projects/Research/Observability/_Metrics/tempo-query.yaml:/etc/tempo-query.yaml"
  #   command: --grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml
  #   networks:
  #     - loki

  # mongo:
  #   image: mongo:4.2

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
  #   environment:
  #     - http.host=0.0.0.0
  #     - discovery.type=single-node
  #     - ES_JAVA_OPTS=-Xms512m -Xmx512m
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.10.0
  #   environment:
  #     - SERVER_HOST=0.0.0.0
  #   ports:
  #     - "5601:5601"
  #   links:
  #     - elasticsearch 

  elasticsearch:
   container_name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
   networks:
    - loki

  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:7.9.2
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://localhost:9200
   networks:
    - loki

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.9.2
    command: metricbeat -e -strict.perms=false
    # environment: 
    #   - setup.kibana.host=kibana:5601
    #   - output.elasticsearch.hosts=["elasticsearch:9200"]
    volumes:
      - "D:/projects/Research/Observability/_Metrics/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro" 
      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro" 
      - "/proc:/hostfs/proc:ro" 
      - "/:/hostfs:ro"
    networks:
      - loki

volumes:
  elasticsearch-data:

  # graylog:
  #   image: graylog/graylog:4.0
  #   environment:
  #     - 'GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/'
  #   ports:
  #     - "9000:9000"
  #     - "12201:12201/udp"
  #     - "1514:1514"
  #   depends_on: 
  #     - "mongo"
  #     - "elasticsearch"
  #   links:
  #     - "mongo:database"
  #     - "elasticsearch:elastic"
