# cron expression to run in daemon mode. (default; "" = runs only once)
cron: "*/10 * * * *"

# runs the synchronisation on startup
runOnStart: true

origin:
  # url of the origin instance
  url: https://10.0.0.47
  # apiPath: define an api path if other than "/control"
  insecureSkipVerify: true # disable tls check
  username: user
  password: password

# replica instance (optional, if only one)
# replica:
#   # url of the replica instance
#   url: https://10.0.0.47
#   insecureSkipVerify: true
#   username: user
#   password: password
#   autosetup: true

# replicas instances (optional, if more than one)
replicas:
  # url of the replica instance
  - url: https://10.0.0.62
    username: user
    password: password
    autosetup: true
    insecureSkipVerify: true
  - url: https://10.0.0.100:4433
    username: user
    password: password
    insecureSkipVerify: true
    autosetup: true # if true, AdGuardHome is automatically initialized. 

# Configure the sync API server, disabled if api port is 0
api:
  # Port, default 8080
  port: 8080
  # if username and password are defined, basic auth is applied to the sync API 
  # username: user
  # password: password

# Configure sync features; by default all features are enabled.
features:
  generalSettings: true
  queryLogConfig: true
  statsConfig: true
  clientSettings: true
  services: true
  filters: true
  dhcp:
    serverConfig: true
    staticLeases: true
  dns:
    serverConfig: true
    accessLists: true
    rewrites: true
