server:
  http_listen_port: 9080
  grpc_listen_port: 0
        
positions:
  filename: /tmp/positions.yaml
        
client:
  # url: https://162153:eyJrIjoiMGRkZGFmMGU4MDg3NGM5NjBkZDVjYjQzNjdjYmUzNTFiNmY5N2UyMSIsIm4iOiJMb2tpIChEZXYpIiwiaWQiOjU5OTU2Mn0=@logs-prod-eu-west-0.grafana.net/api/prom/push
  url: http://loki:3100
        
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/**/*.log
