version: "3.9"
services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync:latest
    container_name: adguardhome-sync
    command: run --config /config/adguardhome-sync.yaml
    volumes:
      - ./sync-config/adguardhome-sync.yaml:/config/adguardhome-sync.yaml
    ports:
      - 8080:8080
    restart: unless-stopped
    pull_policy: always
    environment:
      - ADGUARDHOME_SYNC_USER:$ADGUARDHOME_SYNC_USER
      - ADGUARDHOME_SYNC_PASSWORD:$ADGUARDHOME_SYNC_PASSWORD
    env_file:
      - ./.env

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    ports:
      - 53:53/tcp 
      - 53:53/udp
#      - 67:67/udp 
#      - 68:68/udp
      - 80:80/tcp 
      - 443:443/tcp 
      - 443:443/udp 
      - 3000:3000/tcp
      - 853:853/tcp
#      - 784:784/udp 
#      - 853:853/udp 
#      - 8853:8853/udp
#      - 5443:5443/tcp 
#      - 5443:5443/udp
    restart: unless-stopped
    pull_policy: always
